### ISSUE TITLE
Filter names with dashes truncated 

### ISSUE THREAD

**Issue by Linwood-F** [JonathanMaccollum/PsXisfReader#1]
get-xisflightframes (and perhaps others) appear to truncate the value for Filter if the filter name contains a dash.

For example, I have "Ha-5nm" as a name and that shows in the fits header in PI, but when read by this routine it comes out "Ha-".

**Comment by JonathanMaccollum** [comment]
Thanks for reporting.  I have modified the code to opt-in for truncating the bandpass from the filter names in version 1.0.49.
Update-Module PsXisfReader -Force

Keep in mind, cached reads on the files may still have the older versions, so clear any Cache.clixml files that may have been generated through existing runs.
